s

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -239,10 +239,10 @@ steps:
     - echo "Running SonarQube analysis for Backend - QA..."
     - apt-get update && apt-get install -y curl
     - chmod +x analyze-backend-sonar-dev.sh
-    - SONAR_CONFIG=sonar-project-backend-qa.properties ./analyze-backend-sonar-dev.sh
+    - ./analyze-backend-sonar-dev.sh
     - echo "Backend SonarQube analysis completed"
 
-- name: sonar-frontend-qa
+- name: sonar-frontend-dev
   image: openjdk:17-jdk-slim
   environment:
     SONAR_HOST_URL: "http://34.46.73.44:9003"
@@ -253,8 +253,14 @@ steps:
     - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
     - apt-get install -y nodejs
     - npm install -g sonar-scanner
-    - echo "Running SonarQube analysis for Frontend - QA..."
-    - npx sonar-scanner -Dsonar.projectKey=frontend-hospital-qa-drone -Dsonar.host.url=http://34.46.73.44:9003 -Dsonar.login=sqa_9e95b3a3e0b243715a9b438fb7a08c1060e7123a -Dsonar.sources=src -Dsonar.tests=src/components/__tests__ -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
+    - echo "Running SonarQube analysis for Frontend - DEV..."
+    - npx sonar-scanner -Dsonar.projectKey=frontend-hospital-dev-drone -Dsonar.host.url=http://34.46.73.44:9003 -Dsonar.login=sqa_9e95b3a3e0b243715a9b438fb7a08c1060e7123a -Dsonar.sources=src -Dsonar.tests=src/components/__tests__ -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.qualitygate.wait=true
+    - SONAR_EXIT_CODE=$?
+    - if [ $SONAR_EXIT_CODE -ne 0 ]; then
+        echo "ERROR: El análisis de SonarQube del frontend falló con código de salida $SONAR_EXIT_CODE";
+        echo "El pipeline de Drone fallará debido a problemas de calidad detectados por SonarQube en el frontend";
+        exit $SONAR_EXIT_CODE;
+      fi
     - echo "Frontend SonarQube analysis completed"
 
 - name: build-docker-backend-qa
